name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '5 4 1,8,15,22,27 * *'
permissions:
  contents: write
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Fetch latest data
      run: |-
        pip install icalendar pytz beautifulsoup4
        python script.py
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git commit -m "Latest data" || exit 0
        git diff HEAD^ HEAD | git commit --amend -F -
        git push
